name: Rust CI/CD

on:
  push:
    branches: ["main"]
    tags:
      - "v*" # Trigger release job on tags like v1.0.0
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always # Keep Cargo output colored

jobs:
  # -----------------------------------------------------------------
  # JOB 1: CI - Build and Test (Windows)
  # Runs on every push to main and every pull request
  # -----------------------------------------------------------------
  build_and_test:
    name: Build & Test (Windows)
    runs-on: windows-latest # Windows runner for standard CI checks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable # Use latest stable Rust
          target: x86_64-pc-windows-msvc # Windows target

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/
            ~/.cargo/git/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build project
        run: cargo build --verbose # Builds for the Windows platform

      - name: Run tests
        run: cargo test --verbose # Runs tests for the Windows platform

  # -----------------------------------------------------------------
  # JOB 2: CD - Build MSI and Release (Windows)
  # Runs ONLY when a tag (e.g., v1.0.0) is pushed
  # -----------------------------------------------------------------
  build_msi_and_release:
    name: Build MSI & Release (Windows)
    runs-on: windows-latest # Dedicated Windows runner for MSI creation

    # This job only runs if the trigger was a tag push
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc # Essential for Windows .exe and MSI

      - name: Cache Cargo dependencies (Windows)
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/
            ~/.cargo/git/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install cargo-wix
        run: cargo install cargo-wix --force
      - name: Install WiX Toolset
        run: |
          Invoke-WebRequest -Uri "https://github.com/wixtoolset/wix3/releases/download/wix3141rtm/wix314.exe" -OutFile "wix314.exe"
          Start-Process -FilePath "wix314.exe" -ArgumentList "/install","/quiet" -Wait

      - name: Verify WiX Toolset Installation
        run: |
          where candle.exe
          if ($LastExitCode -ne 0) {
              echo "Candle.exe not found in PATH after WiX Toolset installation."
              exit 1
          }

      - name: Build MSI Installer
        # This will build the Rust executable for Windows and then package it into an MSI
        run: |
          cargo build --release
          cargo wix

      - name: Get Release Information
        id: release_info
        run: |
          $TAG_NAME = "${{ github.ref }}" -replace "refs/tags/", ""
          echo "tag_name=$TAG_NAME" >> "$env:GITHUB_OUTPUT"
          $APP_NAME = "AIPokerCoach"
          echo "app_name=$APP_NAME" >> "$env:GITHUB_OUTPUT"

      - name: List generated files
        run: |
          echo "Checking for generated MSI files:"
          Get-ChildItem -Path "target" -Recurse -Filter "*.msi" | ForEach-Object { Write-Host $_.FullName }

      - name: Upload MSI to Release
        uses: softprops/action-gh-release@v2
        # This 'if' ensures it only runs if the job itself was triggered by a tag (redundant but harmless)
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ steps.release_info.outputs.tag_name }}
          name: Release ${{ steps.release_info.outputs.app_name }} ${{ steps.release_info.outputs.tag_name }}
          generate_release_notes: true # Generates release notes from Git history
          files: |
            target/wix/AIPokerCoach-${{ steps.release_info.outputs.tag_name }}-x86_64.msi
            target/wix/AIPokerCoach-${{ steps.release_info.outputs.tag_name }}.msi
            # Include both possible naming patterns
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
